In [5]:
import numpy as np
from numpy.linalg import inv, LinAlgError
import matplotlib.pyplot as plt

In [40]:
class LinearRegression:
    def __init__(self):
        self._coefficients = None

    # x is a matrix and y is a vector
    def fit(self, X,y):
        X = np.asarray(X)
        y = np.asarray(y)

        X = np.c_[np.ones(X.shape[0]), X]
        try:
            self._coefficients = inv(X.T @ X) @ X.T @ y 
        except LinAlgError:
            raise ValueError("Matrices are not invertible")

    def predict(self, X):
        if self._coefficients is None:
            return "Model is not trained yet"
        X = np.asarray(X)
        X = np.c_[np.ones(X.shape[0]), X]  # Add intercept
        return X @ self._coefficients

    def print_coefficients(self):
        return self._coefficients

In [41]:
model = LinearRegression()
# Generate 100 samples, 3 features (X) and corresponding target variable (y)
X = np.random.rand(100, 3) * 10  # Features scaled between 0-10
y = 3*X[:,0] + 2*X[:,1] + X[:,2] + np.random.normal(0, 1, 100)  # Linear relationship with noise

print("Features:\n", X[:5])
print("Target:\n", y[:5])

Features:
 [[9.58473929 7.50271307 1.57902904]
 [3.20708773 0.82286922 4.41880731]
 [9.7105568  7.63903646 1.74678122]
 [2.12557492 6.78786829 9.00872414]
 [9.99179178 8.69814212 3.24930509]]
Target:
 [45.58704736 14.99538961 44.6402079  29.56365047 50.26602682]


In [42]:
model.fit(X,y)
y_pred = model.predict(X)

In [43]:
y_bar = y.mean()
y_bar_array = np.full(len(y), y_bar)
r_squared = 1 - (sum((y - y_pred)**2)/sum((y_pred - y_bar_array)**2))

In [44]:
r_squared

0.9917985636440823

In [45]:
print(model._coefficients)

[0.00857478 2.97575894 2.02971729 0.99869126]
