In [7]:
import numpy as np
from scipy.linalg import inv
import matplotlib.pyplot as plt

In [41]:
class LinearRegression:
    def __init__(self):
        pass

    # x is a matrix and y is a vector
    def fit(self, X,y):
        self._coefficients = inv(X.T @ X) @ X.T @ y 

    def predict(self, X):
        return X @ self._coefficients 


In [42]:
model = LinearRegression()
# Generate 100 samples, 3 features (X) and corresponding target variable (y)
X = np.random.rand(100, 3) * 10  # Features scaled between 0-10
y = 3*X[:,0] + 2*X[:,1] + X[:,2] + np.random.normal(0, 1, 100)  # Linear relationship with noise

print("Features:\n", X[:5])
print("Target:\n", y[:5])

Features:
 [[7.5617322  6.70579831 2.93333789]
 [2.17312745 6.00673734 6.87717467]
 [4.53207168 0.72570549 5.11358049]
 [7.47800337 0.85468132 7.5448217 ]
 [6.63773774 7.70969439 7.46213751]]
Target:
 [38.05163406 24.56457668 21.81714369 31.07450532 41.95433304]


In [43]:
model.fit(X,y)
y_pred = model.predict(X)

In [44]:
y_bar = y.mean()
y_bar_array = np.full(len(y), y_bar)
r_squared = 1 - (sum((y - y_pred)**2)/sum((y_pred - y_bar_array)**2))

In [45]:
r_squared

0.9907782202134195